"""
Number guessing game written by Uchegbu Somtochukwu on June 2nd 2020

"""

import random

def random_guess_even(random_number,number):
    if random_number % 2 == 0:
        print('Wrong guess. Hint: random number is an even')
        
def random_guess_odd(random_number,number):
    if random_number % 2 == 1:
        print('Wrong guess. Hint: random number is an odd')
  

def negative_number(random_number,number):
    if number < 0:
        print('You have entered a negative number, try again')
        
def mini_game():
    max_count = 6
    curr_count = 1
    print('This is a game where you will have to guess a random number generated by the computer\n'
          'The random number will be in range of 1 to 30\n'
          'For every wrong guess you get a hint of the number you did not guess rightly\n'
          'You have {} tries to guess the correct number'
          'At the end if you get the number correctly the game ends\n'
          'When you feel you are tired of playing, to exit the game input 1234\n'
          'If you wish to restart there is option for you'.format(max_count-1))
    
    random_number = random.randint(0, 30)
    print(random_number)
    
    while True:
        number = int(input('Enter your number: '))
        negative_number(random_number,number)
        
        if number == random_number:
            if curr_count ==  0:
                print('Wow, You got it in one go! Amazing')
            else:
                print('Correct guess, you guessed it after {} tries!!'.format(curr_count))
            retry = input('Enter yes to retry enter no to abort program: ')
            if retry == 'yes':
                curr_count = 0
                True
            elif retry == 'no':
                print('Thank you for your time')
                quit()
            else:
                print('Invalid input')
                True
        elif number in range(0, 30):
            if number in range(0,10):               
                random_guess_even(random_number,number)
                random_guess_odd(random_number,number)
                if random_number in range(0,10): print('Number is also between 0 and 10')
                else: print('Number is not between 0 and 10')
            elif number in range(10,20):               
                random_guess_even(random_number,number)
                random_guess_odd(random_number,number)
                if random_number in range(10,20): print('Number is also between 10 and 20')
                else: print('Number is not between 10 and 20')
            else:
                random_guess_even(random_number,number)
                random_guess_odd(random_number,number)
                if random_number in range(20,30): print('Number is also between 20 and 30')
                else: print('Number is not between 20 and 30')
            print('You have used {} guesses, keep guessing!!'.format(curr_count))
        elif number == 1234:
            print('Thank you for your time')
            quit()
        elif number not in range(0, 30):
            print('The number you entered is invalid because it is not between 0 and 30')
            
        curr_count+=1
        if curr_count == max_count-1:
            print('One last guess, make it count!')
            
        elif curr_count == max_count:
            print('You have run out of guesses, the correct guess is {}'.format(random_number))
            quit()
            
        
            

mini_game()
